// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp7GqO1q13KyPRxmQifkUXwZTLz5Seguc',
    appId: '1:849855858531:web:9519be4c88379f05697556',
    messagingSenderId: '849855858531',
    projectId: 'goaly-app-39631',
    authDomain: 'goaly-app-39631.firebaseapp.com',
    storageBucket: 'goaly-app-39631.firebasestorage.app',
    measurementId: 'G-EPCW16HQP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_YLkLMIo-RNJa40vIJv9GaAnpzXVnvMo',
    appId: '1:849855858531:android:24a14e38e54152c3697556',
    messagingSenderId: '849855858531',
    projectId: 'goaly-app-39631',
    storageBucket: 'goaly-app-39631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnDFvYgQF5GPk4XbwYjYAg4taxUFe2x3o',
    appId: '1:849855858531:ios:e93a5f8cdfbb775a697556',
    messagingSenderId: '849855858531',
    projectId: 'goaly-app-39631',
    storageBucket: 'goaly-app-39631.firebasestorage.app',
    iosBundleId: 'com.example.goalyApp',
  );
}
